title = "WomBot Building"
baseURL = "https://hackwimbledon.github.io/wombot"
languageCode = "en-gb"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 
googleAnalytics = ""
enableRobotsTXT = true
publishDir = "../public"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "We're building the WomBot for PiWars"
  facebook = ""
  twitter = "https://twitter.com/WomBotBuilding"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/wombot_early.jpg"
  recent_posts_number = 2
